=== tiyasha99/Web_tech_lab/lab6dtd.dtd
<!ELEMENT Homepage (ProductsList)>
<!ELEMENT ProductsList (Product+)>
<!ELEMENT Product (Image, Code, StockQty, Price, AddtoCartButton, BuyButton)>
<!ELEMENT Code (#PCDATA)>
<!ELEMENT StockQty (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ELEMENT AddtoCartButton (#PCDATA)>
<!ELEMENT BuyButton (#PCDATA)>
<!ELEMENT Image (#PCDATA)>

=== tiyasha99/Web_tech_lab/lab6.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="lab6xsl.xsl" ?>
<!DOCTYPE Homepage SYSTEM "lab6dtd.dtd">
<Homepage>
<ProductsList>
  <Product>
    <Image>https://picsum.photos/200/300?random=1</Image>
    <Code>2941</Code>
    <StockQty>65</StockQty>
    <Price>1500</Price>
    <AddtoCartButton>Add to Cart</AddtoCartButton>
    <BuyButton>Buy Now</BuyButton>
  </Product>
  <Product>
    <Image>https://picsum.photos/200/300?random=1</Image>
    <Code>2941</Code>
    <StockQty>65</StockQty>
    <Price>1500</Price>
    <AddtoCartButton>Add to Cart</AddtoCartButton>
    <BuyButton>Buy Now</BuyButton>
  </Product>
  <Product>
    <Image>https://picsum.photos/200/300?random=1</Image>
    <Code>2942</Code>
    <StockQty>68</StockQty>
    <Price>2500</Price>
    <AddtoCartButton>Add to Cart</AddtoCartButton>
    <BuyButton>Buy Now</BuyButton>
  </Product>
  <Product>
    <Image>https://picsum.photos/200/300?random=1</Image>
    <Code>2943</Code>
    <StockQty>85</StockQty>
    <Price>500</Price>
    <AddtoCartButton>Add to Cart</AddtoCartButton>
    <BuyButton>Buy Now</BuyButton>
  </Product>
  <Product>
    <Image>https://picsum.photos/200/300?random=1</Image>
    <Code>2944</Code>
    <StockQty>86</StockQty>
    <Price>1580</Price>
    <AddtoCartButton>Add to Cart</AddtoCartButton>
    <BuyButton>Buy Now</BuyButton>
  </Product>
</ProductsList>
</Homepage>
